text = """The apple doesn't fall. ...
All that glitters are not gold. ...
A picture is worth a thousand words. ...
Beggers can't be choosers. ...
A bird in the hand. ...
Better safe than sorry. ...
An apple a day keeps the doctor away. ...
Blood is thicker than water. ..."""
lines = text.split("\n")
count = 0
for line in lines:
    if line.startswith("B"):
        count += 1
print("Total number of lines:", len(lines))
print("Number of Sentences that start with letter B:", count)
